spring:
  application:
    name: accounts
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts
    username: admin
    password: admin
    pool-size: 30
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false

server:
  port: 8081

security:
  basic:
    enabled: false
  oauth2:
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true

feign:
  hystrix:
    enabled: false